In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7314, 836, 4299, 5371],
 [7314, 836, 4299, 9867],
 [7314, 5648, 4299, 5667],
 [9464, 1372, 6271, 3585, 3778],
 [9464, 1372, 6271, 3585, 6803],
 [6437, 7314, 3618, 4299, 8979],
 [624, 2822, 9738, 3585]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7314  836 4299 5371]
 [   0    0    0    0 7314  836 4299 9867]
 [   0    0    0    0 7314 5648 4299 5667]
 [   0    0    0 9464 1372 6271 3585 3778]
 [   0    0    0 9464 1372 6271 3585 6803]
 [   0    0    0 6437 7314 3618 4299 8979]
 [   0    0    0    0  624 2822 9738 3585]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 95ms/step


array([[[-0.03134006, -0.01462039, -0.03869237,  0.04977776,
         -0.03257797, -0.01830735, -0.04284367, -0.00999343,
          0.00056988,  0.02509146],
        [-0.03134006, -0.01462039, -0.03869237,  0.04977776,
         -0.03257797, -0.01830735, -0.04284367, -0.00999343,
          0.00056988,  0.02509146],
        [-0.03134006, -0.01462039, -0.03869237,  0.04977776,
         -0.03257797, -0.01830735, -0.04284367, -0.00999343,
          0.00056988,  0.02509146],
        [-0.03134006, -0.01462039, -0.03869237,  0.04977776,
         -0.03257797, -0.01830735, -0.04284367, -0.00999343,
          0.00056988,  0.02509146],
        [ 0.03470044,  0.01016428,  0.01055411, -0.01498884,
          0.04660555, -0.04601765, -0.04934479,  0.02970919,
          0.01107579,  0.04901667],
        [ 0.00937296, -0.04147578,  0.01998415,  0.03700731,
          0.03477461, -0.0151569 , -0.01547655,  0.02259816,
          0.00346838,  0.02614962],
        [-0.02056709,  0.00787544, -0.03008095,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7314,  836, 4299, 5371])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 43ms/step


array([[-0.03134006, -0.01462039, -0.03869237,  0.04977776, -0.03257797,
        -0.01830735, -0.04284367, -0.00999343,  0.00056988,  0.02509146],
       [-0.03134006, -0.01462039, -0.03869237,  0.04977776, -0.03257797,
        -0.01830735, -0.04284367, -0.00999343,  0.00056988,  0.02509146],
       [-0.03134006, -0.01462039, -0.03869237,  0.04977776, -0.03257797,
        -0.01830735, -0.04284367, -0.00999343,  0.00056988,  0.02509146],
       [-0.03134006, -0.01462039, -0.03869237,  0.04977776, -0.03257797,
        -0.01830735, -0.04284367, -0.00999343,  0.00056988,  0.02509146],
       [ 0.03470044,  0.01016428,  0.01055411, -0.01498884,  0.04660555,
        -0.04601765, -0.04934479,  0.02970919,  0.01107579,  0.04901667],
       [ 0.00937296, -0.04147578,  0.01998415,  0.03700731,  0.03477461,
        -0.0151569 , -0.01547655,  0.02259816,  0.00346838,  0.02614962],
       [-0.02056709,  0.00787544, -0.03008095,  0.03058453, -0.041643  ,
        -0.0080322 ,  0.02016231,  0.02069483